/* automatically generated by rust-bindgen 0.72.1 */

pub const PRISM_VERSION_MAJOR: u32 = 0;
pub const PRISM_VERSION_MINOR: u32 = 18;
pub const PRISM_VERSION_PATCH: u32 = 1;
pub const PRISM_VERSION_STRING: &[u8; 7] = b"0.18.1\0";
pub const PRISM_CONFIG_VERSION: u32 = 3;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismContext {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismBackend {
    _unused: [u8; 0],
}
pub type PrismBackendId = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismRegistry {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismRegistryBuilder {
    _unused: [u8; 0],
}
pub type PrismAvailabilityCallback = ::core::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::libc::c_void,
        backend: PrismBackendId,
        name: *const ::libc::c_char,
        available: bool,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismConfig {
    pub version: u8,
    pub registry: *mut PrismRegistry,
    pub availability_callback: PrismAvailabilityCallback,
    pub availability_userdata: *mut ::libc::c_void,
    pub availability_poll_interval_ms: u32,
    pub availability_debounce_samples: u32,
    pub availability_backoff_max_ms: u32,
    pub availability_auto_power_manage: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismConfig"][::core::mem::size_of::<PrismConfig>() - 48usize];
    ["Alignment of PrismConfig"][::core::mem::align_of::<PrismConfig>() - 8usize];
    ["Offset of field: PrismConfig::version"]
        [::core::mem::offset_of!(PrismConfig, version) - 0usize];
    ["Offset of field: PrismConfig::registry"]
        [::core::mem::offset_of!(PrismConfig, registry) - 8usize];
    ["Offset of field: PrismConfig::availability_callback"]
        [::core::mem::offset_of!(PrismConfig, availability_callback) - 16usize];
    ["Offset of field: PrismConfig::availability_userdata"]
        [::core::mem::offset_of!(PrismConfig, availability_userdata) - 24usize];
    ["Offset of field: PrismConfig::availability_poll_interval_ms"]
        [::core::mem::offset_of!(PrismConfig, availability_poll_interval_ms) - 32usize];
    ["Offset of field: PrismConfig::availability_debounce_samples"]
        [::core::mem::offset_of!(PrismConfig, availability_debounce_samples) - 36usize];
    ["Offset of field: PrismConfig::availability_backoff_max_ms"]
        [::core::mem::offset_of!(PrismConfig, availability_backoff_max_ms) - 40usize];
    ["Offset of field: PrismConfig::availability_auto_power_manage"]
        [::core::mem::offset_of!(PrismConfig, availability_auto_power_manage) - 44usize];
};
impl Default for PrismConfig {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const PRISM_OK: PrismError = 0;
pub const PRISM_ERROR_NOT_INITIALIZED: PrismError = 1;
pub const PRISM_ERROR_INVALID_PARAM: PrismError = 2;
pub const PRISM_ERROR_NOT_IMPLEMENTED: PrismError = 3;
pub const PRISM_ERROR_NO_VOICES: PrismError = 4;
pub const PRISM_ERROR_VOICE_NOT_FOUND: PrismError = 5;
pub const PRISM_ERROR_SPEAK_FAILURE: PrismError = 6;
pub const PRISM_ERROR_MEMORY_FAILURE: PrismError = 7;
pub const PRISM_ERROR_RANGE_OUT_OF_BOUNDS: PrismError = 8;
pub const PRISM_ERROR_INTERNAL: PrismError = 9;
pub const PRISM_ERROR_NOT_SPEAKING: PrismError = 10;
pub const PRISM_ERROR_NOT_PAUSED: PrismError = 11;
pub const PRISM_ERROR_ALREADY_PAUSED: PrismError = 12;
pub const PRISM_ERROR_INVALID_UTF8: PrismError = 13;
pub const PRISM_ERROR_INVALID_OPERATION: PrismError = 14;
pub const PRISM_ERROR_ALREADY_INITIALIZED: PrismError = 15;
pub const PRISM_ERROR_BACKEND_NOT_AVAILABLE: PrismError = 16;
pub const PRISM_ERROR_UNKNOWN: PrismError = 17;
pub const PRISM_ERROR_INVALID_AUDIO_FORMAT: PrismError = 18;
pub const PRISM_ERROR_INTERNAL_BACKEND_LIMIT_EXCEEDED: PrismError = 19;
pub const PRISM_ERROR_BACKEND_ENTERED_UNDEFINED_STATE: PrismError = 20;
pub const PRISM_ERROR_LIBRARY_LOAD_FAILED: PrismError = 21;
pub const PRISM_ERROR_LIBRARY_INVALID: PrismError = 22;
pub const PRISM_ERROR_INCOMPATIBLE_ABI: PrismError = 23;
pub const PRISM_ERROR_COUNT: PrismError = 24;
pub type PrismError = ::libc::c_int;
pub type PrismAudioCallback = ::core::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::libc::c_void,
        samples: *const f32,
        sample_count: usize,
        channels: usize,
        sample_rate: usize,
    ),
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PrismBackendVTable {
    pub size: usize,
    pub create: ::core::option::Option<
        unsafe extern "C" fn(userdata: *mut ::libc::c_void) -> *mut ::libc::c_void,
    >,
    pub destroy: ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void)>,
    pub is_supported:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> bool>,
    pub initialize:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> PrismError>,
    pub speak: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            text: *const ::libc::c_char,
            interrupt: bool,
        ) -> PrismError,
    >,
    pub speak_to_memory: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            text: *const ::libc::c_char,
            callback: PrismAudioCallback,
            callback_userdata: *mut ::libc::c_void,
        ) -> PrismError,
    >,
    pub braille: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            text: *const ::libc::c_char,
        ) -> PrismError,
    >,
    pub output: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            text: *const ::libc::c_char,
            interrupt: bool,
        ) -> PrismError,
    >,
    pub stop:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> PrismError>,
    pub pause:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> PrismError>,
    pub resume:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> PrismError>,
    pub is_speaking: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_speaking: *mut bool) -> PrismError,
    >,
    pub set_volume: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, volume: f32) -> PrismError,
    >,
    pub get_volume: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_volume: *mut f32) -> PrismError,
    >,
    pub set_rate: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, rate: f32) -> PrismError,
    >,
    pub get_rate: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_rate: *mut f32) -> PrismError,
    >,
    pub set_pitch: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, pitch: f32) -> PrismError,
    >,
    pub get_pitch: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_pitch: *mut f32) -> PrismError,
    >,
    pub refresh_voices:
        ::core::option::Option<unsafe extern "C" fn(instance: *mut ::libc::c_void) -> PrismError>,
    pub count_voices: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_count: *mut usize) -> PrismError,
    >,
    pub get_voice_name: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            voice_id: usize,
            out_name: *mut *const ::libc::c_char,
        ) -> PrismError,
    >,
    pub get_voice_language: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            voice_id: usize,
            out_language: *mut *const ::libc::c_char,
        ) -> PrismError,
    >,
    pub set_voice: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, voice_id: usize) -> PrismError,
    >,
    pub get_voice: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_voice_id: *mut usize) -> PrismError,
    >,
    pub get_channels: ::core::option::Option<
        unsafe extern "C" fn(instance: *mut ::libc::c_void, out_channels: *mut usize) -> PrismError,
    >,
    pub get_sample_rate: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            out_sample_rate: *mut usize,
        ) -> PrismError,
    >,
    pub get_bit_depth: ::core::option::Option<
        unsafe extern "C" fn(
            instance: *mut ::libc::c_void,
            out_bit_depth: *mut usize,
        ) -> PrismError,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismBackendVTable"][::core::mem::size_of::<PrismBackendVTable>() - 224usize];
    ["Alignment of PrismBackendVTable"][::core::mem::align_of::<PrismBackendVTable>() - 8usize];
    ["Offset of field: PrismBackendVTable::size"]
        [::core::mem::offset_of!(PrismBackendVTable, size) - 0usize];
    ["Offset of field: PrismBackendVTable::create"]
        [::core::mem::offset_of!(PrismBackendVTable, create) - 8usize];
    ["Offset of field: PrismBackendVTable::destroy"]
        [::core::mem::offset_of!(PrismBackendVTable, destroy) - 16usize];
    ["Offset of field: PrismBackendVTable::is_supported"]
        [::core::mem::offset_of!(PrismBackendVTable, is_supported) - 24usize];
    ["Offset of field: PrismBackendVTable::initialize"]
        [::core::mem::offset_of!(PrismBackendVTable, initialize) - 32usize];
    ["Offset of field: PrismBackendVTable::speak"]
        [::core::mem::offset_of!(PrismBackendVTable, speak) - 40usize];
    ["Offset of field: PrismBackendVTable::speak_to_memory"]
        [::core::mem::offset_of!(PrismBackendVTable, speak_to_memory) - 48usize];
    ["Offset of field: PrismBackendVTable::braille"]
        [::core::mem::offset_of!(PrismBackendVTable, braille) - 56usize];
    ["Offset of field: PrismBackendVTable::output"]
        [::core::mem::offset_of!(PrismBackendVTable, output) - 64usize];
    ["Offset of field: PrismBackendVTable::stop"]
        [::core::mem::offset_of!(PrismBackendVTable, stop) - 72usize];
    ["Offset of field: PrismBackendVTable::pause"]
        [::core::mem::offset_of!(PrismBackendVTable, pause) - 80usize];
    ["Offset of field: PrismBackendVTable::resume"]
        [::core::mem::offset_of!(PrismBackendVTable, resume) - 88usize];
    ["Offset of field: PrismBackendVTable::is_speaking"]
        [::core::mem::offset_of!(PrismBackendVTable, is_speaking) - 96usize];
    ["Offset of field: PrismBackendVTable::set_volume"]
        [::core::mem::offset_of!(PrismBackendVTable, set_volume) - 104usize];
    ["Offset of field: PrismBackendVTable::get_volume"]
        [::core::mem::offset_of!(PrismBackendVTable, get_volume) - 112usize];
    ["Offset of field: PrismBackendVTable::set_rate"]
        [::core::mem::offset_of!(PrismBackendVTable, set_rate) - 120usize];
    ["Offset of field: PrismBackendVTable::get_rate"]
        [::core::mem::offset_of!(PrismBackendVTable, get_rate) - 128usize];
    ["Offset of field: PrismBackendVTable::set_pitch"]
        [::core::mem::offset_of!(PrismBackendVTable, set_pitch) - 136usize];
    ["Offset of field: PrismBackendVTable::get_pitch"]
        [::core::mem::offset_of!(PrismBackendVTable, get_pitch) - 144usize];
    ["Offset of field: PrismBackendVTable::refresh_voices"]
        [::core::mem::offset_of!(PrismBackendVTable, refresh_voices) - 152usize];
    ["Offset of field: PrismBackendVTable::count_voices"]
        [::core::mem::offset_of!(PrismBackendVTable, count_voices) - 160usize];
    ["Offset of field: PrismBackendVTable::get_voice_name"]
        [::core::mem::offset_of!(PrismBackendVTable, get_voice_name) - 168usize];
    ["Offset of field: PrismBackendVTable::get_voice_language"]
        [::core::mem::offset_of!(PrismBackendVTable, get_voice_language) - 176usize];
    ["Offset of field: PrismBackendVTable::set_voice"]
        [::core::mem::offset_of!(PrismBackendVTable, set_voice) - 184usize];
    ["Offset of field: PrismBackendVTable::get_voice"]
        [::core::mem::offset_of!(PrismBackendVTable, get_voice) - 192usize];
    ["Offset of field: PrismBackendVTable::get_channels"]
        [::core::mem::offset_of!(PrismBackendVTable, get_channels) - 200usize];
    ["Offset of field: PrismBackendVTable::get_sample_rate"]
        [::core::mem::offset_of!(PrismBackendVTable, get_sample_rate) - 208usize];
    ["Offset of field: PrismBackendVTable::get_bit_depth"]
        [::core::mem::offset_of!(PrismBackendVTable, get_bit_depth) - 216usize];
};
pub const PRISM_LOG_LEVEL_TRACE: PrismLogLevel = 0;
pub const PRISM_LOG_LEVEL_DEBUG: PrismLogLevel = 1;
pub const PRISM_LOG_LEVEL_INFO: PrismLogLevel = 2;
pub const PRISM_LOG_LEVEL_WARN: PrismLogLevel = 3;
pub const PRISM_LOG_LEVEL_ERROR: PrismLogLevel = 4;
pub const PRISM_LOG_LEVEL_NONE: PrismLogLevel = 5;
pub type PrismLogLevel = ::libc::c_int;
pub type PrismLogCallback = ::core::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::libc::c_void,
        level: PrismLogLevel,
        source: *const ::libc::c_char,
        message: *const ::libc::c_char,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismLogHandler {
    pub fn_: PrismLogCallback,
    pub userdata: *mut ::libc::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismLogHandler"][::core::mem::size_of::<PrismLogHandler>() - 16usize];
    ["Alignment of PrismLogHandler"][::core::mem::align_of::<PrismLogHandler>() - 8usize];
    ["Offset of field: PrismLogHandler::fn_"]
        [::core::mem::offset_of!(PrismLogHandler, fn_) - 0usize];
    ["Offset of field: PrismLogHandler::userdata"]
        [::core::mem::offset_of!(PrismLogHandler, userdata) - 8usize];
};
impl Default for PrismLogHandler {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PrismPluginServices {
    pub struct_size: u32,
    pub reserved: u32,
    pub log: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *const PrismPluginServices,
            level: PrismLogLevel,
            message: *const ::libc::c_char,
        ),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismPluginServices"][::core::mem::size_of::<PrismPluginServices>() - 16usize];
    ["Alignment of PrismPluginServices"][::core::mem::align_of::<PrismPluginServices>() - 8usize];
    ["Offset of field: PrismPluginServices::struct_size"]
        [::core::mem::offset_of!(PrismPluginServices, struct_size) - 0usize];
    ["Offset of field: PrismPluginServices::reserved"]
        [::core::mem::offset_of!(PrismPluginServices, reserved) - 4usize];
    ["Offset of field: PrismPluginServices::log"]
        [::core::mem::offset_of!(PrismPluginServices, log) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismPluginInstanceContext {
    pub struct_size: u32,
    pub reserved: u32,
    pub services: *const PrismPluginServices,
    pub userdata: *mut ::libc::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismPluginInstanceContext"]
        [::core::mem::size_of::<PrismPluginInstanceContext>() - 24usize];
    ["Alignment of PrismPluginInstanceContext"]
        [::core::mem::align_of::<PrismPluginInstanceContext>() - 8usize];
    ["Offset of field: PrismPluginInstanceContext::struct_size"]
        [::core::mem::offset_of!(PrismPluginInstanceContext, struct_size) - 0usize];
    ["Offset of field: PrismPluginInstanceContext::reserved"]
        [::core::mem::offset_of!(PrismPluginInstanceContext, reserved) - 4usize];
    ["Offset of field: PrismPluginInstanceContext::services"]
        [::core::mem::offset_of!(PrismPluginInstanceContext, services) - 8usize];
    ["Offset of field: PrismPluginInstanceContext::userdata"]
        [::core::mem::offset_of!(PrismPluginInstanceContext, userdata) - 16usize];
};
impl Default for PrismPluginInstanceContext {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct PrismPluginHost {
    pub abi_version: u64,
    pub struct_size: u32,
    pub reserved: u32,
    pub log: ::core::option::Option<
        unsafe extern "C" fn(
            self_: *const PrismPluginHost,
            level: PrismLogLevel,
            message: *const ::libc::c_char,
        ),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismPluginHost"][::core::mem::size_of::<PrismPluginHost>() - 24usize];
    ["Alignment of PrismPluginHost"][::core::mem::align_of::<PrismPluginHost>() - 8usize];
    ["Offset of field: PrismPluginHost::abi_version"]
        [::core::mem::offset_of!(PrismPluginHost, abi_version) - 0usize];
    ["Offset of field: PrismPluginHost::struct_size"]
        [::core::mem::offset_of!(PrismPluginHost, struct_size) - 8usize];
    ["Offset of field: PrismPluginHost::reserved"]
        [::core::mem::offset_of!(PrismPluginHost, reserved) - 12usize];
    ["Offset of field: PrismPluginHost::log"]
        [::core::mem::offset_of!(PrismPluginHost, log) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PrismPluginBackend {
    pub abi_version: u64,
    pub struct_size: u32,
    pub reserved: u32,
    pub name: *const ::libc::c_char,
    pub priority: ::libc::c_int,
    pub features: u64,
    pub vtable: *const PrismBackendVTable,
    pub userdata: *mut ::libc::c_void,
    pub plugin_version: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PrismPluginBackend"][::core::mem::size_of::<PrismPluginBackend>() - 64usize];
    ["Alignment of PrismPluginBackend"][::core::mem::align_of::<PrismPluginBackend>() - 8usize];
    ["Offset of field: PrismPluginBackend::abi_version"]
        [::core::mem::offset_of!(PrismPluginBackend, abi_version) - 0usize];
    ["Offset of field: PrismPluginBackend::struct_size"]
        [::core::mem::offset_of!(PrismPluginBackend, struct_size) - 8usize];
    ["Offset of field: PrismPluginBackend::reserved"]
        [::core::mem::offset_of!(PrismPluginBackend, reserved) - 12usize];
    ["Offset of field: PrismPluginBackend::name"]
        [::core::mem::offset_of!(PrismPluginBackend, name) - 16usize];
    ["Offset of field: PrismPluginBackend::priority"]
        [::core::mem::offset_of!(PrismPluginBackend, priority) - 24usize];
    ["Offset of field: PrismPluginBackend::features"]
        [::core::mem::offset_of!(PrismPluginBackend, features) - 32usize];
    ["Offset of field: PrismPluginBackend::vtable"]
        [::core::mem::offset_of!(PrismPluginBackend, vtable) - 40usize];
    ["Offset of field: PrismPluginBackend::userdata"]
        [::core::mem::offset_of!(PrismPluginBackend, userdata) - 48usize];
    ["Offset of field: PrismPluginBackend::plugin_version"]
        [::core::mem::offset_of!(PrismPluginBackend, plugin_version) - 56usize];
};
impl Default for PrismPluginBackend {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type PrismPluginQueryFn = ::core::option::Option<
    unsafe extern "C" fn(host: *const PrismPluginHost, index: usize) -> *const PrismPluginBackend,
>;
pub const PRISM_BACKEND_IS_SUPPORTED_AT_RUNTIME: PrismBackendFeature = 1;
pub const PRISM_BACKEND_SUPPORTS_SPEAK: PrismBackendFeature = 4;
pub const PRISM_BACKEND_SUPPORTS_SPEAK_TO_MEMORY: PrismBackendFeature = 8;
pub const PRISM_BACKEND_SUPPORTS_BRAILLE: PrismBackendFeature = 16;
pub const PRISM_BACKEND_SUPPORTS_OUTPUT: PrismBackendFeature = 32;
pub const PRISM_BACKEND_SUPPORTS_IS_SPEAKING: PrismBackendFeature = 64;
pub const PRISM_BACKEND_SUPPORTS_STOP: PrismBackendFeature = 128;
pub const PRISM_BACKEND_SUPPORTS_PAUSE: PrismBackendFeature = 256;
pub const PRISM_BACKEND_SUPPORTS_RESUME: PrismBackendFeature = 512;
pub const PRISM_BACKEND_SUPPORTS_SET_VOLUME: PrismBackendFeature = 1024;
pub const PRISM_BACKEND_SUPPORTS_GET_VOLUME: PrismBackendFeature = 2048;
pub const PRISM_BACKEND_SUPPORTS_SET_RATE: PrismBackendFeature = 4096;
pub const PRISM_BACKEND_SUPPORTS_GET_RATE: PrismBackendFeature = 8192;
pub const PRISM_BACKEND_SUPPORTS_SET_PITCH: PrismBackendFeature = 16384;
pub const PRISM_BACKEND_SUPPORTS_GET_PITCH: PrismBackendFeature = 32768;
pub const PRISM_BACKEND_SUPPORTS_REFRESH_VOICES: PrismBackendFeature = 65536;
pub const PRISM_BACKEND_SUPPORTS_COUNT_VOICES: PrismBackendFeature = 131072;
pub const PRISM_BACKEND_SUPPORTS_GET_VOICE_NAME: PrismBackendFeature = 262144;
pub const PRISM_BACKEND_SUPPORTS_GET_VOICE_LANGUAGE: PrismBackendFeature = 524288;
pub const PRISM_BACKEND_SUPPORTS_GET_VOICE: PrismBackendFeature = 1048576;
pub const PRISM_BACKEND_SUPPORTS_SET_VOICE: PrismBackendFeature = 2097152;
pub const PRISM_BACKEND_SUPPORTS_GET_CHANNELS: PrismBackendFeature = 4194304;
pub const PRISM_BACKEND_SUPPORTS_GET_SAMPLE_RATE: PrismBackendFeature = 8388608;
pub const PRISM_BACKEND_SUPPORTS_GET_BIT_DEPTH: PrismBackendFeature = 16777216;
pub const PRISM_BACKEND_PERFORMS_SILENCE_TRIMMING_ON_SPEAK: PrismBackendFeature = 33554432;
pub const PRISM_BACKEND_PERFORMS_SILENCE_TRIMMING_ON_SPEAK_TO_MEMORY: PrismBackendFeature =
    67108864;
pub const PRISM_BACKEND_SUPPORTS_SPEAK_SSML: PrismBackendFeature = 134217728;
pub const PRISM_BACKEND_SUPPORTS_SPEAK_TO_MEMORY_SSML: PrismBackendFeature = 268435456;
pub const PRISM_BACKEND_FEATURE_MAX_BIT: PrismBackendFeature = 0;
pub type PrismBackendFeature = ::libc::c_int;
unsafe extern "C" {
    pub fn prism_config_init() -> PrismConfig;
}
unsafe extern "C" {
    pub fn prism_init(cfg: *mut PrismConfig) -> *mut PrismContext;
}
unsafe extern "C" {
    pub fn prism_shutdown(ctx: *mut PrismContext);
}
unsafe extern "C" {
    pub fn prism_availability_poll_pause(ctx: *mut PrismContext);
}
unsafe extern "C" {
    pub fn prism_availability_poll_resume(ctx: *mut PrismContext);
}
unsafe extern "C" {
    pub fn prism_availability_auto_power_supported() -> bool;
}
unsafe extern "C" {
    pub fn prism_registry_count(ctx: *mut PrismContext) -> usize;
}
unsafe extern "C" {
    pub fn prism_registry_id_at(ctx: *mut PrismContext, index: usize) -> PrismBackendId;
}
unsafe extern "C" {
    pub fn prism_registry_id(ctx: *mut PrismContext, name: *const ::libc::c_char)
    -> PrismBackendId;
}
unsafe extern "C" {
    pub fn prism_registry_name(ctx: *mut PrismContext, id: PrismBackendId)
    -> *const ::libc::c_char;
}
unsafe extern "C" {
    pub fn prism_registry_priority(ctx: *mut PrismContext, id: PrismBackendId) -> ::libc::c_int;
}
unsafe extern "C" {
    pub fn prism_registry_exists(ctx: *mut PrismContext, id: PrismBackendId) -> bool;
}
unsafe extern "C" {
    pub fn prism_registry_get(ctx: *mut PrismContext, id: PrismBackendId) -> *mut PrismBackend;
}
unsafe extern "C" {
    pub fn prism_registry_create(ctx: *mut PrismContext, id: PrismBackendId) -> *mut PrismBackend;
}
unsafe extern "C" {
    pub fn prism_registry_create_best(ctx: *mut PrismContext) -> *mut PrismBackend;
}
unsafe extern "C" {
    pub fn prism_registry_acquire(ctx: *mut PrismContext, id: PrismBackendId) -> *mut PrismBackend;
}
unsafe extern "C" {
    pub fn prism_registry_acquire_best(ctx: *mut PrismContext) -> *mut PrismBackend;
}
unsafe extern "C" {
    pub fn prism_backend_free(backend: *mut PrismBackend);
}
unsafe extern "C" {
    pub fn prism_backend_name(backend: *mut PrismBackend) -> *const ::libc::c_char;
}
unsafe extern "C" {
    pub fn prism_backend_get_features(backend: *mut PrismBackend) -> u64;
}
unsafe extern "C" {
    pub fn prism_backend_initialize(backend: *mut PrismBackend) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_speak(
        backend: *mut PrismBackend,
        text: *const ::libc::c_char,
        interrupt: bool,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_speak_to_memory(
        backend: *mut PrismBackend,
        text: *const ::libc::c_char,
        callback: PrismAudioCallback,
        userdata: *mut ::libc::c_void,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_braille(
        backend: *mut PrismBackend,
        text: *const ::libc::c_char,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_output(
        backend: *mut PrismBackend,
        text: *const ::libc::c_char,
        interrupt: bool,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_stop(backend: *mut PrismBackend) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_pause(backend: *mut PrismBackend) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_resume(backend: *mut PrismBackend) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_is_speaking(
        backend: *mut PrismBackend,
        out_speaking: *mut bool,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_set_volume(backend: *mut PrismBackend, volume: f32) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_set_rate(backend: *mut PrismBackend, rate: f32) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_set_pitch(backend: *mut PrismBackend, pitch: f32) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_volume(backend: *mut PrismBackend, out_volume: *mut f32)
    -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_rate(backend: *mut PrismBackend, out_rate: *mut f32) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_pitch(backend: *mut PrismBackend, out_pitch: *mut f32) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_refresh_voices(backend: *mut PrismBackend) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_count_voices(
        backend: *mut PrismBackend,
        out_count: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_voice_name(
        backend: *mut PrismBackend,
        voice_id: usize,
        out_name: *mut *const ::libc::c_char,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_voice_language(
        backend: *mut PrismBackend,
        voice_id: usize,
        out_language: *mut *const ::libc::c_char,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_set_voice(backend: *mut PrismBackend, voice_id: usize) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_voice(
        backend: *mut PrismBackend,
        out_voice_id: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_channels(
        backend: *mut PrismBackend,
        out_channels: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_sample_rate(
        backend: *mut PrismBackend,
        out_sample_rate: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_backend_get_bit_depth(
        backend: *mut PrismBackend,
        out_bit_depth: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_error_string(error: PrismError) -> *const ::libc::c_char;
}
unsafe extern "C" {
    pub fn prism_registry_builder_new() -> *mut PrismRegistryBuilder;
}
unsafe extern "C" {
    pub fn prism_registry_builder_add_backend(
        builder: *mut PrismRegistryBuilder,
        name: *const ::libc::c_char,
        priority: ::libc::c_int,
        features: u64,
        vtable: *const PrismBackendVTable,
        userdata: *mut ::libc::c_void,
        userdata_free: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::libc::c_void)>,
        out_id: *mut PrismBackendId,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_registry_builder_add_library(
        builder: *mut PrismRegistryBuilder,
        path: *const ::libc::c_char,
        priority_override: ::libc::c_int,
        out_count: *mut usize,
    ) -> PrismError;
}
unsafe extern "C" {
    pub fn prism_registry_freeze(builder: *mut PrismRegistryBuilder) -> *mut PrismRegistry;
}
unsafe extern "C" {
    pub fn prism_registry_builder_free(builder: *mut PrismRegistryBuilder);
}
unsafe extern "C" {
    pub fn prism_registry_retain(registry: *mut PrismRegistry) -> *mut PrismRegistry;
}
unsafe extern "C" {
    pub fn prism_registry_release(registry: *mut PrismRegistry);
}
unsafe extern "C" {
    pub fn prism_set_log_handler(handler: PrismLogHandler) -> PrismLogHandler;
}
unsafe extern "C" {
    pub fn prism_set_log_level(level: PrismLogLevel) -> PrismLogLevel;
}
unsafe extern "C" {
    pub fn prism_log(
        level: PrismLogLevel,
        source: *const ::libc::c_char,
        message: *const ::libc::c_char,
    );
}
unsafe extern "C" {
    pub fn prism_log_flush();
}
unsafe extern "C" {
    pub fn prism_log_shutdown();
}
unsafe extern "C" {
    pub fn prism_version() -> u32;
}
unsafe extern "C" {
    pub fn prism_version_string() -> *const ::libc::c_char;
}
